version: "3"
services:
    media-postgresql:
        image: postgres:11
        environment:
            - POSTGRES_USER=openslides
            - POSTGRES_PASSWORD=openslides
            - POSTGRES_DB=openslides
    media:
        image: openslides-media-dev
        environment:
            - MEDIA_DATABASE_HOST=media-postgresql
            - MEDIA_DATABASE_PORT=5432
            - MEDIA_DATABASE_NAME=openslides
            - MEDIA_DATABASE_USER=openslides
            - MEDIA_DATABASE_PASSWORD=openslides
            - CHECK_REQUEST_URL=test/
        volumes:
            - ./src:/app/src
        ports:
            - 8000:8000
    tests:
        image: openslides-media-tests
        volumes:
            - ./tests:/app/tests

